/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ParticleDefinition } from '../types/physics';

export const C_SPEED_PIXELS_PER_NS = 240; 
export const COULOMB_K_SCALE = 3200;

export const PARTICLE_REGISTRY: Record<string, ParticleDefinition> = {
  // ==================== QUARKS ====================
  up_quark: {
    id: 'up_quark',
    name: 'Up Quark',
    symbol: 'u',
    category: 'quark',
    generation: 1,
    restMassMeV: 2.16,
    charge: 2 / 3,
    spin: '1/2',
    radius: 5,
    color: '#38bdf8', // light blue
    secondaryColor: '#7dd3fc',
    description: 'First-generation quark with +2/3e charge. Main constituent of protons and neutrons.',
  },
  down_quark: {
    id: 'down_quark',
    name: 'Down Quark',
    symbol: 'd',
    category: 'quark',
    generation: 1,
    restMassMeV: 4.67,
    charge: -1 / 3,
    spin: '1/2',
    radius: 5.5,
    color: '#0284c7', // medium blue
    secondaryColor: '#38bdf8',
    description: 'First-generation quark with -1/3e charge. Present in nucleons.',
  },
  charm_quark: {
    id: 'charm_quark',
    name: 'Charm Quark',
    symbol: 'c',
    category: 'quark',
    generation: 2,
    restMassMeV: 1270.0,
    charge: 2 / 3,
    spin: '1/2',
    radius: 7,
    color: '#6366f1', // indigo
    secondaryColor: '#818cf8',
    description: 'Second-generation heavy quark discovered at SLAC/BNL in J/psi meson.',
  },
  strange_quark: {
    id: 'strange_quark',
    name: 'Strange Quark',
    symbol: 's',
    category: 'quark',
    generation: 2,
    restMassMeV: 93.4,
    charge: -1 / 3,
    spin: '1/2',
    radius: 6,
    color: '#8b5cf6', // violet
    secondaryColor: '#a78bfa',
    description: 'Second-generation quark with strange quantum number S = -1.',
  },
  top_quark: {
    id: 'top_quark',
    name: 'Top Quark',
    symbol: 't',
    category: 'quark',
    generation: 3,
    restMassMeV: 172760.0, // Extremely heavy ~173 GeV!
    charge: 2 / 3,
    spin: '1/2',
    radius: 10,
    color: '#d946ef', // fuchsia
    secondaryColor: '#e879f9',
    description: 'Heaviest known fundamental particle (as heavy as an atom of gold). Decays before hadronizing.',
  },
  bottom_quark: {
    id: 'bottom_quark',
    name: 'Bottom Quark (Beauty)',
    symbol: 'b',
    category: 'quark',
    generation: 3,
    restMassMeV: 4180.0,
    charge: -1 / 3,
    spin: '1/2',
    radius: 8,
    color: '#ec4899', // pink
    secondaryColor: '#f472b6',
    description: 'Third-generation quark with mass ~4.18 GeV, central to CP-violation research at LHCb.',
  },

  // ==================== LEPTONS ====================
  electron: {
    id: 'electron',
    name: 'Electron',
    symbol: 'e⁻',
    category: 'lepton',
    generation: 1,
    restMassMeV: 0.51099895,
    charge: -1,
    spin: '1/2',
    radius: 6,
    color: '#06b6d4', // laser cyan
    secondaryColor: '#22d3ee',
    description: 'Stable first-generation lepton. Fundamental building block of atomic shells.',
  },
  positron: {
    id: 'positron',
    name: 'Positron',
    symbol: 'e⁺',
    category: 'lepton',
    generation: 1,
    restMassMeV: 0.51099895,
    charge: 1,
    spin: '1/2',
    radius: 6,
    color: '#f59e0b', // amber
    secondaryColor: '#fbbf24',
    description: 'Antiparticle of the electron. Annihilates with electron into 2 or 3 gamma rays.',
    isAntiparticle: true,
  },
  electron_neutrino: {
    id: 'electron_neutrino',
    name: 'Electron Neutrino',
    symbol: 'νₑ',
    category: 'lepton',
    generation: 1,
    restMassMeV: 0.0000008, // < 0.8 eV
    charge: 0,
    spin: '1/2',
    radius: 4,
    color: '#94a3b8', // light slate ghost
    secondaryColor: '#cbd5e1',
    description: 'Nearly massless, neutral first-generation lepton interacting solely via weak force.',
  },
  muon_minus: {
    id: 'muon_minus',
    name: 'Muon',
    symbol: 'μ⁻',
    category: 'lepton',
    generation: 2,
    restMassMeV: 105.658,
    charge: -1,
    spin: '1/2',
    radius: 7.5,
    color: '#14b8a6', // teal
    secondaryColor: '#2dd4bf',
    description: 'Second-generation lepton (~207x electron mass) produced in atmospheric cosmic rays.',
  },
  muon_plus: {
    id: 'muon_plus',
    name: 'Antimuon',
    symbol: 'μ⁺',
    category: 'lepton',
    generation: 2,
    restMassMeV: 105.658,
    charge: 1,
    spin: '1/2',
    radius: 7.5,
    color: '#f97316', // orange
    secondaryColor: '#fb923c',
    description: 'Antiparticle of the muon with positive elementary charge.',
    isAntiparticle: true,
  },
  muon_neutrino: {
    id: 'muon_neutrino',
    name: 'Muon Neutrino',
    symbol: 'ν_μ',
    category: 'lepton',
    generation: 2,
    restMassMeV: 0.00017,
    charge: 0,
    spin: '1/2',
    radius: 4,
    color: '#64748b',
    secondaryColor: '#94a3b8',
    description: 'Neutral second-generation lepton produced in pion and muon decays.',
  },
  tau_minus: {
    id: 'tau_minus',
    name: 'Tau Lepton',
    symbol: 'τ⁻',
    category: 'lepton',
    generation: 3,
    restMassMeV: 1776.86,
    charge: -1,
    spin: '1/2',
    radius: 8.5,
    color: '#10b981', // emerald
    secondaryColor: '#34d399',
    description: 'Third-generation massive lepton (~3,477x electron mass), able to decay hadronically.',
  },
  tau_neutrino: {
    id: 'tau_neutrino',
    name: 'Tau Neutrino',
    symbol: 'ν_τ',
    category: 'lepton',
    generation: 3,
    restMassMeV: 0.0182,
    charge: 0,
    spin: '1/2',
    radius: 4,
    color: '#475569',
    secondaryColor: '#64748b',
    description: 'Third-generation neutrino discovered by DONUT experiment at Fermilab (2000).',
  },

  // ==================== GAUGE BOSONS (FORCE CARRIERS) ====================
  photon: {
    id: 'photon',
    name: 'Photon',
    symbol: 'γ',
    category: 'gauge_boson',
    restMassMeV: 0,
    charge: 0,
    spin: '1',
    radius: 5,
    color: '#eab308', // yellow/gold ray
    secondaryColor: '#fde047',
    description: 'Gauge boson mediator of the electromagnetic interaction. Travels strictly at c.',
  },
  gluon: {
    id: 'gluon',
    name: 'Gluon',
    symbol: 'g',
    category: 'gauge_boson',
    restMassMeV: 0,
    charge: 0,
    spin: '1',
    radius: 5.5,
    color: '#ef4444', // red
    secondaryColor: '#f87171',
    description: 'Massless vector boson mediating the strong nuclear interaction carrying color charge.',
  },
  w_plus: {
    id: 'w_plus',
    name: 'W⁺ Boson',
    symbol: 'W⁺',
    category: 'gauge_boson',
    restMassMeV: 80377.0, // 80.4 GeV
    charge: 1,
    spin: '1',
    radius: 9,
    color: '#3b82f6', // blue
    secondaryColor: '#60a5fa',
    description: 'Massive charged vector boson mediating weak flavor transitions and beta decay.',
  },
  w_minus: {
    id: 'w_minus',
    name: 'W⁻ Boson',
    symbol: 'W⁻',
    category: 'gauge_boson',
    restMassMeV: 80377.0,
    charge: -1,
    spin: '1',
    radius: 9,
    color: '#0ea5e9', // sky blue
    secondaryColor: '#38bdf8',
    description: 'Negative charge counterpart of the W boson.',
    isAntiparticle: true,
  },
  z_boson: {
    id: 'z_boson',
    name: 'Z⁰ Boson',
    symbol: 'Z⁰',
    category: 'gauge_boson',
    restMassMeV: 91187.6, // 91.2 GeV
    charge: 0,
    spin: '1',
    radius: 9.5,
    color: '#a855f7', // purple
    secondaryColor: '#c084fc',
    description: 'Neutral massive gauge boson of the electroweak interaction, observed at CERN SPS.',
  },

  // ==================== SCALAR BOSON ====================
  higgs_boson: {
    id: 'higgs_boson',
    name: 'Higgs Boson',
    symbol: 'H⁰',
    category: 'scalar_boson',
    restMassMeV: 125250.0, // 125.25 GeV
    charge: 0,
    spin: '0',
    radius: 11,
    color: '#fb7185', // rose
    secondaryColor: '#fda4af',
    description: 'Excitation of the Higgs field responsible for electroweak symmetry breaking and particle masses.',
  },

  // ==================== COMPOSITES & NUCLEAR PARTICLES ====================
  proton: {
    id: 'proton',
    name: 'Proton',
    symbol: 'p⁺',
    category: 'baryon',
    restMassMeV: 938.272,
    charge: 1,
    spin: '1/2',
    radius: 10,
    color: '#2563eb', // royal blue
    secondaryColor: '#3b82f6',
    description: 'Stable baryon composed of uud quarks bound by gluons.',
  },
  antiproton: {
    id: 'antiproton',
    name: 'Antiproton',
    symbol: 'p̄⁻',
    category: 'baryon',
    restMassMeV: 938.272,
    charge: -1,
    spin: '1/2',
    radius: 10,
    color: '#e11d48', // crimson
    secondaryColor: '#f43f5e',
    description: 'Baryonic antiparticle composed of ūūd̄ antiquarks.',
    isAntiparticle: true,
  },
  neutron: {
    id: 'neutron',
    name: 'Neutron',
    symbol: 'n⁰',
    category: 'baryon',
    restMassMeV: 939.565,
    charge: 0,
    spin: '1/2',
    radius: 10,
    color: '#64748b', // slate
    secondaryColor: '#94a3b8',
    description: 'Neutral baryon composed of udd quarks. Undergoes beta decay with ~14.7 min mean life when free.',
  },
  alpha: {
    id: 'alpha',
    name: 'Alpha Particle (⁴He²⁺)',
    symbol: 'α²⁺',
    category: 'nucleus',
    restMassMeV: 3727.379,
    charge: 2,
    spin: '0',
    radius: 13,
    color: '#9333ea', // deep purple
    secondaryColor: '#a855f7',
    description: 'Helium-4 nucleus composed of two tightly bound protons and two neutrons.',
  },
  pion_neutral: {
    id: 'pion_neutral',
    name: 'Neutral Pion',
    symbol: 'π⁰',
    category: 'meson',
    restMassMeV: 134.9768,
    charge: 0,
    spin: '0',
    radius: 6.5,
    color: '#e2e8f0',
    secondaryColor: '#cbd5e1',
    description: 'Lightest meson (uū - dd̄)/√2, decays rapidly into 2 photons (mean life 8.5 x 10⁻¹⁷ s).',
  },
  pion_plus: {
    id: 'pion_plus',
    name: 'Positive Pion',
    symbol: 'π⁺',
    category: 'meson',
    restMassMeV: 139.5704,
    charge: 1,
    spin: '0',
    radius: 6.5,
    color: '#0284c7',
    secondaryColor: '#38bdf8',
    description: 'Charged pseudoscalar meson composed of ud̄ quarks.',
  },
  gold_nucleus: {
    id: 'gold_nucleus',
    name: 'Gold-197 Nucleus',
    symbol: '¹⁹⁷Au⁷⁹⁺',
    category: 'nucleus',
    restMassMeV: 183432.5,
    charge: 79,
    spin: '3/2',
    radius: 18,
    nuclearRadiusFm: 7.28,
    atomicNumberZ: 79,
    massNumberA: 197,
    color: '#eab308', // gold
    secondaryColor: '#facc15',
    description: 'Heavy bare nuclear target used in Rutherford scattering experiments.',
  },

  // ==================== ATOMS (NEUTRAL ATOMIC SYSTEMS) ====================
  atom_hydrogen: {
    id: 'atom_hydrogen',
    name: 'Hydrogen Atom (¹H)',
    symbol: '¹H',
    category: 'atom',
    restMassMeV: 938.783,
    charge: 0,
    spin: '1/2',
    radius: 12,
    nuclearRadiusFm: 0.841,
    atomicRadiusPm: 53.0,
    atomicNumberZ: 1,
    massNumberA: 1,
    electronShells: [1],
    color: '#38bdf8', // radiant cyan gas
    secondaryColor: '#7dd3fc',
    description: 'Lightest atomic system: 1 proton nucleus surrounded by 1 bound electron in the ground 1s orbital.',
  },
  atom_gold: {
    id: 'atom_gold',
    name: 'Gold Atom (¹⁹⁷Au)',
    symbol: '¹⁹⁷Au',
    category: 'atom',
    restMassMeV: 183472.9,
    charge: 0,
    spin: '3/2',
    radius: 26,
    nuclearRadiusFm: 7.28,
    atomicRadiusPm: 144.0,
    atomicNumberZ: 79,
    massNumberA: 197,
    electronShells: [2, 8, 18, 32, 18, 1],
    color: '#f59e0b', // warm gold amber
    secondaryColor: '#fde047',
    description: 'Heavy gold atom with 79 protons and 118 neutrons, surrounded by 6 concentric electron shells [Xe] 4f¹⁴ 5d¹⁰ 6s¹.',
  },
  atom_silicon: {
    id: 'atom_silicon',
    name: 'Silicon Atom (²⁸Si)',
    symbol: '²⁸Si',
    category: 'atom',
    restMassMeV: 26067.5,
    charge: 0,
    spin: '0',
    radius: 17,
    nuclearRadiusFm: 3.80,
    atomicRadiusPm: 111.0,
    atomicNumberZ: 14,
    massNumberA: 28,
    electronShells: [2, 8, 4],
    color: '#06b6d4', // crystalline cyan
    secondaryColor: '#22d3ee',
    description: 'Semiconductor atom with 14 protons and 14 electrons; core component of vertex tracking silicon strip detectors.',
  },
  atom_aluminum: {
    id: 'atom_aluminum',
    name: 'Aluminum Atom (²⁷Al)',
    symbol: '²⁷Al',
    category: 'atom',
    restMassMeV: 25139.7,
    charge: 0,
    spin: '5/2',
    radius: 19,
    nuclearRadiusFm: 3.75,
    atomicRadiusPm: 143.0,
    atomicNumberZ: 13,
    massNumberA: 27,
    electronShells: [2, 8, 3],
    color: '#a855f7', // iridescent violet-silver
    secondaryColor: '#c084fc',
    description: 'Light metal target atom with 13 protons and 14 neutrons; used in accelerator vacuum tubes and drift chambers.',
  },

  custom: {
    id: 'custom',
    name: 'Custom Particle',
    symbol: 'X*',
    category: 'custom',
    restMassMeV: 50.0,
    charge: 1,
    spin: '1/2',
    radius: 8,
    color: '#8b5cf6',
    secondaryColor: '#a78bfa',
    description: 'User-calibrated particle with freely adjustable mass and charge.',
  },
};

