/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ExperimentPreset } from '../types/physics';

export const EXPERIMENT_PRESETS: ExperimentPreset[] = [
  {
    id: 'relativistic_billiards',
    title: 'Relativistic Angle Squeeze',
    subtitle: 'Equal-mass elastic scattering below the classical 90° limit',
    badge: 'Special Relativity',
    description:
      'In classical mechanics, elastic scattering of identical masses with a stationary target always yields an opening angle of exactly 90°. At near-light speed (β = 0.92c), Lorentz boost contraction squeezes the opening angle to strictly less than 90°: tan(θ₁)tan(θ₂) = 2/(γ+1).',
    theoryNotes: [
      'Classical limit (v ≪ c): θ₁ + θ₂ = 90.0°',
      'Relativistic formula: tan(θ₁) · tan(θ₂) = 2 / (γ + 1) < 1',
      'At β = 0.92c, γ ≈ 2.55, opening angle collapses to ~65°–75°!',
      'Mandelstam variable t denotes momentum transfer squared.',
    ],
    particleA: 'electron',
    particleB: 'electron',
    betaA: 0.92,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 14,
    coulombEnabled: true,
    reactionsEnabled: false,
    coulombStrength: 1.0,
    defaultSlowMo: 0.02,
    focusHighlights: ['Lorentz angle contraction', 'Opening angle < 90°', 'Mandelstam t transfer'],
  },
  {
    id: 'higgs_production',
    title: 'Higgs Boson Production',
    subtitle: 'Vector Boson Fusion: W⁺ + W⁻ → H⁰ (125.25 GeV)',
    badge: 'Electroweak Sector',
    description:
      'High-energy collision of massive weak vector bosons (W⁺ and W⁻) fusing to produce the scalar Higgs Boson (H⁰) at center-of-mass energy √(s) = 125.25 GeV.',
    theoryNotes: [
      'Scalar Higgs mass: m_H = 125.25 GeV/c²',
      'Mediated by electroweak Yukawa coupling: λ = m_f / v',
      'Confirms the spontaneous symmetry breaking mechanism (CERN LHC 2012).',
    ],
    particleA: 'w_plus',
    particleB: 'w_minus',
    betaA: 0.82,
    betaB: 0.82,
    angleADeg: 0,
    angleBDeg: 180,
    impactParameter: 0,
    coulombEnabled: true,
    reactionsEnabled: true,
    coulombStrength: 0.8,
    defaultSlowMo: 0.01,
    focusHighlights: ['Higgs mechanism', 'Vector boson fusion', 'Scalar resonance'],
  },
  {
    id: 'top_quark_pair',
    title: 'Top Quark Pair Creation',
    subtitle: 'Ultra-heavy quark production: g + g → t + t̄ (345.5 GeV)',
    badge: 'Quantum Chromodynamics',
    description:
      'Gluon-gluon fusion generating a top and antitop quark pair. With a rest mass of ~172.8 GeV/c² each, top quarks are the heaviest elementary particles known, decaying via weak interaction before forming hadrons.',
    theoryNotes: [
      'Threshold invariant mass: √(s) ≥ 2 · 172.76 GeV = 345.5 GeV',
      'Strong coupling α_s mediates gluon fusion vertex.',
      'Top lifetime τ ≈ 5 × 10⁻²⁵ s is shorter than hadronization timescale.',
    ],
    particleA: 'gluon',
    particleB: 'gluon',
    betaA: 1.0,
    betaB: 1.0,
    angleADeg: 0,
    angleBDeg: 180,
    impactParameter: 0,
    coulombEnabled: false,
    reactionsEnabled: true,
    coulombStrength: 1.0,
    defaultSlowMo: 0.008,
    focusHighlights: ['Top quark rest mass', 'Gluon-gluon fusion', 'Sub-hadronic decay'],
  },
  {
    id: 'annihilation_ee',
    title: 'Electron-Positron Annihilation',
    subtitle: 'Matter-antimatter conversion into gamma rays: e⁻ + e⁺ → 2γ',
    badge: 'Quantum Electrodynamics',
    description:
      'An electron and positron collide and annihilate into two high-energy photons. In the laboratory frame, relativistic Doppler beaming concentrates the photons in the forward direction.',
    theoryNotes: [
      'Reaction: e⁻ + e⁺ → γ + γ',
      'In CoM frame: E_γ* = √(s) / 2',
      'Total rest mass converted completely into pure photon kinetic energy.',
    ],
    particleA: 'electron',
    particleB: 'positron',
    betaA: 0.85,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 0,
    coulombEnabled: true,
    reactionsEnabled: true,
    coulombStrength: 1.2,
    defaultSlowMo: 0.015,
    focusHighlights: ['Mass-energy conversion (E=mc²)', 'Doppler blueshift', 'Photon pair'],
  },
  {
    id: 'rutherford_scattering',
    title: 'Rutherford Alpha Backscattering',
    subtitle: 'Hyperbolic Coulomb repulsion: He²⁺ on ¹⁹⁷Au⁷⁹⁺',
    badge: 'Nuclear Physics',
    description:
      'Alpha particle (⁴He²⁺) incident upon a massive Gold nucleus (¹⁹⁷Au⁷⁹⁺). High nuclear charge Z=79 creates immense Coulomb repulsion, causing large-angle backscattering (>90°).',
    theoryNotes: [
      'Differential cross-section: dσ/dΩ = (z₁z₂e² / 4E_k)² / sin⁴(θ/2)',
      'Exact distance of closest approach r_min calculated mathematically at collision center.',
      'Demonstrated the concentrated positive nucleus of the atom (1911).',
    ],
    particleA: 'alpha',
    particleB: 'gold_nucleus',
    betaA: 0.70,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 18,
    coulombEnabled: true,
    reactionsEnabled: false,
    coulombStrength: 1.5,
    defaultSlowMo: 0.02,
    focusHighlights: ['Hyperbolic orbit', 'Closest approach r_min', 'Backscattering'],
  },
  {
    id: 'tau_creation',
    title: 'Tau Lepton Pair Creation',
    subtitle: 'Heavy lepton generation: e⁻ + e⁺ → τ⁻ + τ⁺ (3.55 GeV)',
    badge: 'Lepton Sector',
    description:
      'High-energy electron-positron collider collision creating a pair of tau leptons (m_τ = 1,777 MeV/c²), confirming the third generation of fermions.',
    theoryNotes: [
      'Threshold √(s) ≥ 2 · 1,776.86 MeV = 3.55 GeV',
      'Discovered by Martin Perl at SPEAR / SLAC (Nobel Prize 1995).',
    ],
    particleA: 'electron',
    particleB: 'positron',
    betaA: 0.999,
    betaB: 0.999,
    angleADeg: 0,
    angleBDeg: 180,
    impactParameter: 0,
    coulombEnabled: true,
    reactionsEnabled: true,
    coulombStrength: 1.0,
    defaultSlowMo: 0.005,
    focusHighlights: ['3rd generation leptons', 'Collider kinematics', 'High invariant mass'],
  },
  {
    id: 'compton_scattering',
    title: 'Compton Photon Scattering',
    subtitle: 'Relativistic photon deflection: γ + e⁻ → γ\' + e⁻\'',
    badge: 'Quantum Optics',
    description:
      'High-energy gamma photon collides with an electron. Relativistic momentum conservation induces a wavelength shift Δλ = (h/mc)(1 - cos θ).',
    theoryNotes: [
      'Scattered photon energy: E\' = E / [1 + (E / m_e c²)(1 - cos θ)]',
      'Klein-Nishina differential cross section governs angular probability.',
    ],
    particleA: 'photon',
    particleB: 'electron',
    betaA: 1.0,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 12,
    coulombEnabled: false,
    reactionsEnabled: true,
    coulombStrength: 0.5,
    defaultSlowMo: 0.02,
    focusHighlights: ['Photon momentum transfer', 'Recoil electron', 'Klein-Nishina'],
  },
  {
    id: 'proton_antiproton',
    title: 'Proton-Antiproton Annihilation',
    subtitle: 'Hadronic annihilation yielding pion showers: p + p̄ → 3π',
    badge: 'Hadron Collider',
    description:
      'Proton and antiproton collide head-on at relativistic speeds. Constituent valence quarks annihilate into gluons, fragmenting into neutral and charged pions.',
    theoryNotes: [
      'Total available energy: √(s) ≈ 1.88 GeV in CoM frame',
      'Simulates the core discovery physics of the CERN SppS collider.',
    ],
    particleA: 'proton',
    particleB: 'antiproton',
    betaA: 0.88,
    betaB: 0.88,
    angleADeg: 0,
    angleBDeg: 180,
    impactParameter: 2,
    coulombEnabled: true,
    reactionsEnabled: true,
    coulombStrength: 1.0,
    defaultSlowMo: 0.01,
    focusHighlights: ['Baryon-antibaryon annihilation', 'Pion shower', 'Quark-gluon vertex'],
  },
  {
    id: 'rutherford_gold_atom',
    title: 'Rutherford Gold Atom Scattering',
    subtitle: 'Alpha projectile entering heavy Gold (¹⁹⁷Au) atomic field',
    badge: 'Atomic Physics',
    description:
      'High-velocity alpha particle (⁴He²⁺) directed at a heavy Gold atom (¹⁹⁷Au). Visualizes large-angle Coulomb backscattering caused by the concentrated positive nuclear charge within the 6-shell electron cloud.',
    theoryNotes: [
      'Rutherford differential cross section: dσ/dΩ ∝ (Z₁ Z₂ e² / 4E)² · 1 / sin⁴(θ/2)',
      'Nuclear charge Z = 79 produces immense electrostatic deflection.',
      'Demonstrates the nuclear model: atomic radius (144 pm) is ~20,000× larger than the nucleus (7.3 fm)!',
    ],
    particleA: 'alpha',
    particleB: 'atom_gold',
    betaA: 0.65,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 8,
    coulombEnabled: true,
    reactionsEnabled: false,
    coulombStrength: 1.2,
    defaultSlowMo: 0.015,
    focusHighlights: ['Z=79 nuclear repulsion', 'Large angle backscatter', 'Electron cloud shell'],
  },
  {
    id: 'hydrogen_dissociation',
    title: 'Hydrogen Target Ionization',
    subtitle: 'Relativistic proton impacting neutral Hydrogen (¹H)',
    badge: 'Ionization Dynamics',
    description:
      'A relativistic proton beam penetrates the single-electron 1s orbital cloud of atomic Hydrogen, demonstrating impact ionization and Coulomb deflection.',
    theoryNotes: [
      'Target: 1 proton nucleus + 1 ground-state electron (Bohr radius a₀ ≈ 53 pm).',
      'Momentum transfer induces orbital excitation or prompt ionization.',
    ],
    particleA: 'proton',
    particleB: 'atom_hydrogen',
    betaA: 0.85,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 10,
    coulombEnabled: true,
    reactionsEnabled: true,
    coulombStrength: 1.0,
    defaultSlowMo: 0.02,
    focusHighlights: ['Single-electron 1s shell', 'Bohr radius scale', 'Ionization threshold'],
  },
  {
    id: 'silicon_tracker_impact',
    title: 'Silicon Detector Scattering',
    subtitle: 'Electron beam interacting with Silicon (²⁸Si) lattice atom',
    badge: 'Detector Physics',
    description:
      'Simulates relativistic electron trajectories passing through Silicon (Z=14) atoms, modeling the ionization energy loss (dE/dx) that makes modern semiconductor silicon pixel trackers work at the LHC.',
    theoryNotes: [
      'Bethe-Bloch formula governs mean stopping power and ionization yield.',
      '14 electrons in [Ne] 3s² 3p² configuration provide screening of the Z=14 nucleus.',
    ],
    particleA: 'electron',
    particleB: 'atom_silicon',
    betaA: 0.94,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 12,
    coulombEnabled: true,
    reactionsEnabled: false,
    coulombStrength: 1.0,
    defaultSlowMo: 0.02,
    focusHighlights: ['Silicon tracking sensor', 'Multi-shell screening', 'Ionization dE/dx'],
  },
  {
    id: 'aluminum_beam_target',
    title: 'Aluminum Target Collision',
    subtitle: 'Proton beam interaction with Aluminum (²⁷Al) target',
    badge: 'Nuclear Targetry',
    description:
      'Proton colliding with Aluminum (Z=13, A=27), illustrating beam window physics and nuclear cross-sections in accelerator vacuum chambers.',
    theoryNotes: [
      'Aluminum-27 nucleus radius R ≈ 1.25 × 27^(1/3) ≈ 3.75 fm.',
      'Critical material for low-mass accelerator beam pipes and calorimeter collimators.',
    ],
    particleA: 'proton',
    particleB: 'atom_aluminum',
    betaA: 0.88,
    betaB: 0.0,
    angleADeg: 0,
    angleBDeg: 0,
    impactParameter: 14,
    coulombEnabled: true,
    reactionsEnabled: false,
    coulombStrength: 1.0,
    defaultSlowMo: 0.02,
    focusHighlights: ['Beam pipe material', 'Nuclear radius scaling', 'Coulomb barrier'],
  },
];

